-- Tables Creation
CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE notes (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content TEXT,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);